EncontroCampistas.WebSite.Web/Models/EventosViewModel.cs
using EncontroCampistas.Biblioteca.Entidades;
using EncontroCampistas.WebSite.Site.Models;
using System.Collections.Generic;

namespace EncontroCampistas.WebSite.Web.Models
{
    public class EventosViewModel
    {
        public IEnumerable<Evento> Eventos { get; set; }

        public Paginacao Paginacao { get; set; }

        public int EventoAtual { get; set; }
    }
}

EncontroCampistas.WebSite.Web/Areas/Administrativo/Controllers/EventoController.cs
using EncontroCampistas.Biblioteca.Entidades;
using EncontroCampistas.Biblioteca.Repositorio;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncontroCampistas.WebSite.Web.Areas.Administrativo.Controllers
{
    public class EventoController : Controller
    {
        private EventosRepositorio _repositorio;

        // GET: Administrativo/Evento
        public ActionResult Index()
        {
            _repositorio = new EventosRepositorio();
            var eventos = _repositorio.Eventos;
            return View(eventos);
        }


        public ViewResult Alterar(int eventoId)
        {
            _repositorio = new EventosRepositorio();
            Evento evento = _repositorio.Eventos
                .FirstOrDefault(e => e.EventoId == eventoId);

            return View(evento);
        }


        [HttpPost]
        public ActionResult Alterar(Evento evento, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                _repositorio = new EventosRepositorio();
                _repositorio.Salvar(evento);

                TempData["mensagem"] = string.Format("{0} foi salvo com sucesso", evento.Descricao);

                return RedirectToAction("Index");

            }
            return View(evento);
        }

        public ViewResult NovoEvento()
        {
            return View("Alterar", new Evento());
        }

        [HttpPost]
        public JsonResult Excluir(int eventoId)
        {
            // System.Threading.Thread.Sleep(TimeSpan.FromSeconds(5));

            string mensagem = string.Empty;
            _repositorio = new EventosRepositorio();

            Evento objEvento = _repositorio.Excluir(eventoId);

            if (objEvento != null)
            {
                mensagem = string.Format("{0} excluído com sucesso", objEvento.Descricao);
            }

            return Json(mensagem, JsonRequestBehavior.AllowGet);
        }
    }
}

EncontroCampistas.WebSite.Web/Controllers/EventosController.cs
using EncontroCampistas.Biblioteca.Repositorio;
using EncontroCampistas.WebSite.Web.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncontroCampistas.WebSite.Web.Controllers
{
    public class EventosController : Controller
    {
        private EventosRepositorio _repositorio;
        public int EventosPorPagina = 5;
        // GET: Eventos
        public ViewResult ListaEventos(int tipoEvento = -1, int pagina = 1)
        {
            _repositorio = new EventosRepositorio();

            EventosViewModel model = new EventosViewModel
            {
                Eventos = _repositorio.Eventos
                .Where(e => tipoEvento == -1 || e.iTipoEvento == tipoEvento)
                .OrderBy(e => e.Descricao)
                .Skip((pagina - 1) * EventosPorPagina)
                .Take(EventosPorPagina),

                Paginacao = new Site.Models.Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = EventosPorPagina,
                    ItensTotal = _repositorio.Eventos.Count()
                },

                EventoAtual = tipoEvento
            };

            return View(model);
        }
    }
}

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Evento/Alterar.cshtml
@model EncontroCampistas.Biblioteca.Entidades.Evento

@{
    ViewBag.Title = "Alterar " + Model.Descricao;
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

<div class="panel">
    <div class="panel-heading">
        <h3>Alterar @Model.Descricao</h3>
    </div>
    @*Informar senão ao criar não irá achar*@
    @using (Html.BeginForm("Alterar", "Evento", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.EventoId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "EventoId":
                        break;
                    default:
                        <div class="form-group">
                            <label>
                                @(property.DisplayName ?? property.PropertyName)
                            </label>
                            @if (property.PropertyName == "Descricao")
                            {
                                @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>

                        break;
                }
            }
        </div>

        <div class="panel-footer">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            @Html.ActionLink("Cancelar e retornar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Evento/Confirmacao.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel">Exclusão</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" />
                <p>Deseja excluir o evento <em><strong>"<span></span>"</strong></em>&nbsp;?</p>
            </div>

            <div class="modal-footer">
                <button class="btn btn-success" type="button">Confirmar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    $(function () {

        //Abrir o modal

        $(".btn-xs").click(function (e) {
            e.preventDefault();
            var id = this.id;
            var nome = this.name;
            $("#deleteModal .modal-body input[type=hidden]").val(id);
            $("#deleteModal .modal-body span").text(nome);
            $("#deleteModal").modal('show');
        });

        $("#deleteModal .modal-footer button").click(function (e) {
            e.preventDefault();
            var url = "/Administrativo/Evento/Excluir/";
            var id = $(".modal-body input[type=hidden]").val();
            var rowNo = '#row-' + id;

            $.ajax({
                url: url,
                type: 'post',
                dataType: 'json',
                data: { eventoId: id },
                beforeSend: function () {
                    var loading = "<span><em>Excluindo</em>&nbsp;<i class='glyphicon glyphicon-refresh icon-refresh-animate'></i></span>";
                    $('#deleteModal .modal-header h4').after(loading);
                },
                success: function () {

                    $('#deleteModal').modal('hide');

                    $(rowNo).animate({ opacity: 0.0 }, 400, function () {
                        $(rowNo).remove();
                    });
                },
                complete: function (data) {
                    $("#divexcluir").empty();
                    $("#divexcluir").addClass("alert alert-success");
                    $("#divexcluir").html(data.responseText);
                }
            });
        });
    });
</script>

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Evento/Index.cshtml
@model IEnumerable<EncontroCampistas.Biblioteca.Entidades.Evento>

@{
    ViewBag.Title = "Administrativo - Eventos";
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

<div class="alert alert-success" id="mensagem"></div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Encontro Campistas - Administrivo - Eventos</h3>
    </div>
    <div class="panel-body">
        @Html.ActionLink("Novo evento", "NovoEvento", "Evento", new { @class = "btn btn-default" })

        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-right">#Id</th>
                    <th>Descrição</th>
                    <th class="text-right">Data e Hora</th>
                    <th class="text-right">Local</th>
                    <th class="text-right">Duração</th>
                    <th class="text-right">Tipo de Evento</th>
                    <th class="text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="row-@item.EventoId">
                        <td class="text-right">
                            # @item.EventoId
                        </td>
                        <td>
                            @Html.ActionLink(item.Descricao, "Alterar", new { item.EventoId })
                        </td>
                        <td class="text-right">
                            @item.DataHoraRealizacao
                        </td>
                        <td class="text-right">
                            @item.Local
                        </td>
                        <td class="text-right">
                            @item.Duracao
                        </td>
                        <td class="text-right">
                            @*@item.TipoEvento.DescricaoTipoEvento*@
                        </td>
                        <td class="text-center">
                            <input type="submit" class="btn btn-default btn-xs" id="@item.EventoId" name="@item.Descricao" value="Excluir" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

@Html.Partial("Confirmacao")