EncontroCampistas.WebSite.Web/Models/CampistasViewModel.cs
using EncontroCampistas.Biblioteca.Entidades;
using EncontroCampistas.WebSite.Site.Models;
using System.Collections.Generic;

namespace EncontroCampistas.WebSite.Web.Models
{
    public class CampistasViewModel
    {
        public IEnumerable<Campista> Campistas { get; set; }

        public Paginacao Paginacao { get; set; }
    }
}

EncontroCampistas.WebSite.Web/Areas/Administrativo/Controllers/CampistaController.cs
using EncontroCampistas.Biblioteca.Entidades;
using EncontroCampistas.Biblioteca.Repositorio;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncontroCampistas.WebSite.Web.Areas.Administrativo.Controllers
{
    public class CampistaController : Controller
    {
        private CampistasRepositorio _repositorio;

        // GET: Administrativo/Campista
        public ActionResult Index()
        {
            _repositorio = new CampistasRepositorio();
            var campistas = _repositorio.Campistas;
            return View(campistas);
        }


        public ViewResult Alterar(int campistaId)
        {
            _repositorio = new CampistasRepositorio();
            Campista campista = _repositorio.Campistas
                .FirstOrDefault(e => e.CampistaId == campistaId);

            return View(campista);
        }


        [HttpPost]
        public ActionResult Alterar(Campista campista, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                _repositorio = new CampistasRepositorio();
                _repositorio.Salvar(campista);

                TempData["mensagem"] = string.Format("{0} foi salvo com sucesso", campista.Nome);

                return RedirectToAction("Index");

            }
            return View(campista);
        }

        public ViewResult NovoCampista()
        {
            return View("Alterar", new Campista());
        }

        [HttpPost]
        public JsonResult Excluir(int campistaId)
        {
            // System.Threading.Thread.Sleep(TimeSpan.FromSeconds(5));

            string mensagem = string.Empty;
            _repositorio = new CampistasRepositorio();

            Campista objCampista = _repositorio.Excluir(campistaId);

            if (objCampista != null)
            {
                mensagem = string.Format("{0} excluído com sucesso", objCampista.Nome);
            }

            return Json(mensagem, JsonRequestBehavior.AllowGet);
        }
    }
}

EncontroCampistas.WebSite.Web/Controllers/CampistasController.cs
using EncontroCampistas.Biblioteca.Repositorio;
using EncontroCampistas.WebSite.Web.Models;
using System.Linq;
using System.Web.Mvc;

namespace EncontroCampistas.WebSite.Web.Controllers
{
    public class CampistasController : Controller
    {
        private CampistasRepositorio _repositorio;
        public int CampistasPorPagina = 5;
        // GET: Campistas
        public ViewResult ListaCampistas(int pagina = 1)
        {
            _repositorio = new CampistasRepositorio();

            CampistasViewModel model = new CampistasViewModel
            {
                Campistas = _repositorio.Campistas
                .OrderBy(c => c.Nome)
                .Skip((pagina - 1) * CampistasPorPagina)
                .Take(CampistasPorPagina),

                Paginacao = new Site.Models.Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = CampistasPorPagina,
                    ItensTotal = _repositorio.Campistas.Count()
                }
            };

            return View(model);
        }
    }
}

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Campista/Alterar.cshtml
@model EncontroCampistas.Biblioteca.Entidades.Campista

@{
    ViewBag.Title = "Alterar " + Model.Nome;
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

<div class="panel">
    <div class="panel-heading">
        <h3>Alterar @Model.Nome</h3>
    </div>
    @*Informar senão ao criar não irá achar*@
    @using (Html.BeginForm("Alterar", "Campista", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.CampistaId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CampistaId":
                        break;
                    default:
                        <div class="form-group">
                            <label>
                                @(property.DisplayName ?? property.PropertyName)
                            </label>
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>

                        break;
                }
            }
        </div>

        <div class="panel-footer">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            @Html.ActionLink("Cancelar e retornar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Campista/Confirmacao.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel">Exclusão</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" />
                <p>Deseja excluir o campista <em><strong>"<span></span>"</strong></em>&nbsp;?</p>
            </div>

            <div class="modal-footer">
                <button class="btn btn-success" type="button">Confirmar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    $(function () {

        //Abrir o modal

        $(".btn-xs").click(function (e) {
            e.preventDefault();
            var id = this.id;
            var nome = this.name;
            $("#deleteModal .modal-body input[type=hidden]").val(id);
            $("#deleteModal .modal-body span").text(nome);
            $("#deleteModal").modal('show');
        });

        $("#deleteModal .modal-footer button").click(function (e) {
            e.preventDefault();
            var url = "/Administrativo/Campista/Excluir/";
            var id = $(".modal-body input[type=hidden]").val();
            var rowNo = '#row-' + id;

            $.ajax({
                url: url,
                type: 'post',
                dataType: 'json',
                data: { campistaId: id },
                beforeSend: function () {
                    var loading = "<span><em>Excluindo</em>&nbsp;<i class='glyphicon glyphicon-refresh icon-refresh-animate'></i></span>";
                    $('#deleteModal .modal-header h4').after(loading);
                },
                success: function () {

                    $('#deleteModal').modal('hide');

                    $(rowNo).animate({ opacity: 0.0 }, 400, function () {
                        $(rowNo).remove();
                    });
                },
                complete: function (data) {
                    $("#divexcluir").empty();
                    $("#divexcluir").addClass("alert alert-success");
                    $("#divexcluir").html(data.responseText);
                }
            });
        });
    });
</script>

EncontroCampistas.WebSite.Web/Areas/Administrativo/Views/Campista/Index.cshtml
@model IEnumerable<EncontroCampistas.Biblioteca.Entidades.Campista>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

<div class="alert alert-success" id="mensagem"></div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Encontro Campistas - Administrivo - Campistas</h3>
    </div>
    <div class="panel-body">
        @Html.ActionLink("Novo campista", "NovoCampista", "Campista", new { @class = "btn btn-default" })

        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-right">#Id</th>
                    <th>Nome</th>
                    <th>Endereço</th>
                    <th>Número</th>
                    <th>Complemento</th>
                    <th>Bairro</th>
                    <th>Cidade</th>
                    <th>Telefone</th>
                    <th>Celular</th>
                    <th class="text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="row-@item.CampistaId">
                        <td class="text-right">
                            # @item.CampistaId
                        </td>
                        <td>
                            @Html.ActionLink(item.Nome, "Alterar", new { item.CampistaId })
                        </td>
                        <td>
                            @item.Endereco
                        </td>
                        <td>
                            @item.Numero
                        </td>
                        <td>
                            @item.Complemento
                        </td>
                        <td>
                            @item.Bairro
                        </td>
                        <td>
                            @item.Cidade
                        </td>
                        <td>
                            @item.Telefone
                        </td>
                        <td>
                            @item.Celular
                        </td>
                        <td class="text-center">
                            <input type="submit" class="btn btn-default btn-xs" id="@item.CampistaId" name="@item.Nome]" value="Excluir" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

@Html.Partial("Confirmacao")