EncontroCampistas.WebSite.Web/Controllers/TipoEventoController.cs
using EncontroCampistas.Biblioteca.Entidades;
using EncontroCampistas.Biblioteca.Repositorio;
using EncontroCampistas.WebSite.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EncontroCampistas.WebSite.Web.Controllers
{
    public class TipoEventoController : Controller
    {
        private TipoEventoRepositorio _repositorio;

        // GET: TipoEvento
        public PartialViewResult Menu(int tipoEvento = -1)
        {
            ViewBag.tipoEventoSelecionado = tipoEvento;

            _repositorio = new TipoEventoRepositorio();

            TipoEventoViewModel model = new TipoEventoViewModel
            {
                TipoEventos = _repositorio.TipoEventos
                .OrderBy(t => t.DescricaoTipoEvento),
            };

            return PartialView(model);
        }
    }
}

EncontroCampistas.WebSite.Web/Views/Shared/CampistaDetalhes.cshtml
@model EncontroCampistas.Biblioteca.Entidades.Campista

<div class="list-group">
    <a href="#" class="list-group-item">@Model.Nome</a>
</div>

EncontroCampistas.WebSite.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Encontro de Campistas</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErroEstilo.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
        <div class="navbar navbar-inverse" role="navigation">
            <a class="navbar-brand" href="#">1º Encontro de Campistas - 2017</a>

            @Html.Action("Resumo", "Carrinho")
        </div>

        <div class="row panel">
            <div id="eventos" class="col-xs-3">
                @Html.Action("Menu","TipoEvento")
            </div>
            <div id="campistas" class="col-xs-8">@RenderBody()</div>
        </div>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Diocese de Presidente Prudente</p>
        </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>